print('Hello')
print('This is also a string')
print("I'm a string")
print('I\'m a string')
print("I\'m a string")
print('Here is a new line \n and here is the second line')
print("Here is a new line \t and here is the second line")
print(len('Hello world'))
s = "Hello World"
print(s)
print(s[0])
print(s[2])
print(s[2:])
print(s[:2])
print(s[:4])
print(s[4:])
print(s[:-1])
print(s[::-1])
letter = 'zz'
b = letter * 10
print(b)
print(type(b))
